name: Angular S3 Deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
      statuses: write

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Checkout
      uses: actions/checkout@v3
    - name: Get git output names
      id: git
      shell: bash
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=current_branch::$HEAD_REF"
          else
            echo "::set-output name=current_branch::$REF_BRANCH"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
        fi

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: '${{ github.token }}'
        environment: production
        ref: ${{ steps.git.outputs.current_branch }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build app
      run: npm run build

    - name: Deploy to S3
      if: success()
      run: aws s3 sync ./dist/angular-github-actions s3://angular-github-actions --delete

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'success'
        ref: ${{ steps.git.outputs.current_branch }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'failure'
        ref: ${{ steps.git.outputs.current_branch }}